package sogott.tones;

import java.util.stream.Stream;
import java.util.random.RandomGenerator;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ArgumentsSource;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.params.provider.Arguments.arguments;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.closeTo;

final class FrequencyTestArgsProvider {
    final static class NoteAccidentalOctaveFrequency implements ArgumentsProvider {
        @Override
        public Stream<Arguments> provideArguments(ExtensionContext context) {
            return Stream.of(
                    arguments(PitchClass.A, Accidental.FLAT, 0, 25.96),
                    arguments(PitchClass.A, null, 0, 27.5),
                    arguments(PitchClass.A, Accidental.SHARP, 0, 29.14),
                    arguments(PitchClass.A, Accidental.FLAT, 1, 51.91),
                    arguments(PitchClass.A, null, 1, 55),
                    arguments(PitchClass.A, Accidental.SHARP, 1, 58.27),
                    arguments(PitchClass.A, Accidental.FLAT, 2, 103.83),
                    arguments(PitchClass.A, null, 2, 110),
                    arguments(PitchClass.A, Accidental.SHARP, 2, 116.54),
                    arguments(PitchClass.A, Accidental.FLAT, 3, 207.65),
                    arguments(PitchClass.A, null, 3, 220),
                    arguments(PitchClass.A, Accidental.SHARP, 3, 233.08),
                    arguments(PitchClass.A, Accidental.FLAT, 4, 415.3),
                    arguments(PitchClass.A, null, 4, 440),
                    arguments(PitchClass.A, Accidental.SHARP, 4, 466.16),
                    arguments(PitchClass.A, Accidental.FLAT, 5, 830.61),
                    arguments(PitchClass.A, null, 5, 880),
                    arguments(PitchClass.A, Accidental.SHARP, 5, 932.33),
                    arguments(PitchClass.A, Accidental.FLAT, 6, 1661.22),
                    arguments(PitchClass.A, null, 6, 1760),
                    arguments(PitchClass.A, Accidental.SHARP, 6, 1864.66),
                    arguments(PitchClass.A, Accidental.FLAT, 7, 3322.44),
                    arguments(PitchClass.A, null, 7, 3520),
                    arguments(PitchClass.A, Accidental.SHARP, 7, 3729.31),
                    arguments(PitchClass.A, Accidental.FLAT, 8, 6644.88),
                    arguments(PitchClass.A, null, 8, 7040),
                    arguments(PitchClass.A, Accidental.SHARP, 8, 7458.62),
                    arguments(PitchClass.B, Accidental.FLAT, 0, 29.14),
                    arguments(PitchClass.B, null, 0, 30.87),
                    arguments(PitchClass.B, Accidental.SHARP, 0, 32.7),
                    arguments(PitchClass.B, Accidental.FLAT, 1, 58.27),
                    arguments(PitchClass.B, null, 1, 61.74),
                    arguments(PitchClass.B, Accidental.SHARP, 1, 65.41),
                    arguments(PitchClass.B, Accidental.FLAT, 2, 116.54),
                    arguments(PitchClass.B, null, 2, 123.47),
                    arguments(PitchClass.B, Accidental.SHARP, 2, 130.81),
                    arguments(PitchClass.B, Accidental.FLAT, 3, 233.08),
                    arguments(PitchClass.B, null, 3, 246.95),
                    arguments(PitchClass.B, Accidental.SHARP, 3, 261.63),
                    arguments(PitchClass.B, Accidental.FLAT, 4, 466.16),
                    arguments(PitchClass.B, null, 4, 493.88),
                    arguments(PitchClass.B, Accidental.SHARP, 4, 523.25),
                    arguments(PitchClass.B, Accidental.FLAT, 5, 932.33),
                    arguments(PitchClass.B, null, 5, 987.77),
                    arguments(PitchClass.B, Accidental.SHARP, 5, 1046.5),
                    arguments(PitchClass.B, Accidental.FLAT, 6, 1864.66),
                    arguments(PitchClass.B, null, 6, 1975.53),
                    arguments(PitchClass.B, Accidental.SHARP, 6, 2093),
                    arguments(PitchClass.B, Accidental.FLAT, 7, 3729.31),
                    arguments(PitchClass.B, null, 7, 3951.07),
                    arguments(PitchClass.B, Accidental.SHARP, 7, 4186.01),
                    arguments(PitchClass.B, Accidental.FLAT, 8, 7458.62),
                    arguments(PitchClass.B, null, 8, 7902.13),
                    arguments(PitchClass.B, Accidental.SHARP, 8, 8372.02),
                    arguments(PitchClass.C, Accidental.FLAT, 0, 15.43),
                    arguments(PitchClass.C, null, 0, 16.35),
                    arguments(PitchClass.C, Accidental.SHARP, 0, 17.32),
                    arguments(PitchClass.C, Accidental.FLAT, 1, 30.87),
                    arguments(PitchClass.C, null, 1, 32.7),
                    arguments(PitchClass.C, Accidental.SHARP, 1, 34.65),
                    arguments(PitchClass.C, Accidental.FLAT, 2, 61.74),
                    arguments(PitchClass.C, null, 2, 65.41),
                    arguments(PitchClass.C, Accidental.SHARP, 2, 69.3),
                    arguments(PitchClass.C, Accidental.FLAT, 3, 123.47),
                    arguments(PitchClass.C, null, 3, 130.81),
                    arguments(PitchClass.C, Accidental.SHARP, 3, 138.59),
                    arguments(PitchClass.C, Accidental.FLAT, 4, 246.94),
                    arguments(PitchClass.C, null, 4, 261.63),
                    arguments(PitchClass.C, Accidental.SHARP, 4, 277.18),
                    arguments(PitchClass.C, Accidental.FLAT, 5, 493.88),
                    arguments(PitchClass.C, null, 5, 523.25),
                    arguments(PitchClass.C, Accidental.SHARP, 5, 554.37),
                    arguments(PitchClass.C, Accidental.FLAT, 6, 987.77),
                    arguments(PitchClass.C, null, 6, 1046.5),
                    arguments(PitchClass.C, Accidental.SHARP, 6, 1108.73),
                    arguments(PitchClass.C, Accidental.FLAT, 7, 1975.53),
                    arguments(PitchClass.C, null, 7, 2093),
                    arguments(PitchClass.C, Accidental.SHARP, 7, 2217.46),
                    arguments(PitchClass.C, Accidental.FLAT, 8, 3951.07),
                    arguments(PitchClass.C, null, 8, 4186.01),
                    arguments(PitchClass.C, Accidental.SHARP, 8, 4434.92),
                    arguments(PitchClass.D, Accidental.FLAT, 0, 17.32),
                    arguments(PitchClass.D, null, 0, 18.35),
                    arguments(PitchClass.D, Accidental.SHARP, 0, 19.45),
                    arguments(PitchClass.D, Accidental.FLAT, 1, 34.65),
                    arguments(PitchClass.D, null, 1, 36.71),
                    arguments(PitchClass.D, Accidental.SHARP, 1, 38.89),
                    arguments(PitchClass.D, Accidental.FLAT, 2, 69.3),
                    arguments(PitchClass.D, null, 2, 73.42),
                    arguments(PitchClass.D, Accidental.SHARP, 2, 77.78),
                    arguments(PitchClass.D, Accidental.FLAT, 3, 138.59),
                    arguments(PitchClass.D, null, 3, 146.83),
                    arguments(PitchClass.D, Accidental.SHARP, 3, 155.56),
                    arguments(PitchClass.D, Accidental.FLAT, 4, 277.18),
                    arguments(PitchClass.D, null, 4, 293.66),
                    arguments(PitchClass.D, Accidental.SHARP, 4, 311.13),
                    arguments(PitchClass.D, Accidental.FLAT, 5, 554.37),
                    arguments(PitchClass.D, null, 5, 587.33),
                    arguments(PitchClass.D, Accidental.SHARP, 5, 622.25),
                    arguments(PitchClass.D, Accidental.FLAT, 6, 1108.73),
                    arguments(PitchClass.D, null, 6, 1174.66),
                    arguments(PitchClass.D, Accidental.SHARP, 6, 1244.51),
                    arguments(PitchClass.D, Accidental.FLAT, 7, 2217.46),
                    arguments(PitchClass.D, null, 7, 2349.32),
                    arguments(PitchClass.D, Accidental.SHARP, 7, 2489.02),
                    arguments(PitchClass.D, Accidental.FLAT, 8, 4434.92),
                    arguments(PitchClass.D, null, 8, 4698.63),
                    arguments(PitchClass.D, Accidental.SHARP, 8, 4978.03),
                    arguments(PitchClass.E, Accidental.FLAT, 0, 19.45),
                    arguments(PitchClass.E, null, 0, 20.6),
                    arguments(PitchClass.E, Accidental.SHARP, 0, 21.83),
                    arguments(PitchClass.E, Accidental.FLAT, 1, 38.89),
                    arguments(PitchClass.E, null, 1, 41.2),
                    arguments(PitchClass.E, Accidental.SHARP, 1, 43.65),
                    arguments(PitchClass.E, Accidental.FLAT, 2, 77.78),
                    arguments(PitchClass.E, null, 2, 82.41),
                    arguments(PitchClass.E, Accidental.SHARP, 2, 87.31),
                    arguments(PitchClass.E, Accidental.FLAT, 3, 155.56),
                    arguments(PitchClass.E, null, 3, 164.81),
                    arguments(PitchClass.E, Accidental.SHARP, 3, 174.61),
                    arguments(PitchClass.E, Accidental.FLAT, 4, 311.13),
                    arguments(PitchClass.E, null, 4, 329.63),
                    arguments(PitchClass.E, Accidental.SHARP, 4, 349.23),
                    arguments(PitchClass.E, Accidental.FLAT, 5, 622.25),
                    arguments(PitchClass.E, null, 5, 659.25),
                    arguments(PitchClass.E, Accidental.SHARP, 5, 698.46),
                    arguments(PitchClass.E, Accidental.FLAT, 6, 1244.51),
                    arguments(PitchClass.E, null, 6, 1318.51),
                    arguments(PitchClass.E, Accidental.SHARP, 6, 1396.91),
                    arguments(PitchClass.E, Accidental.FLAT, 7, 2489.02),
                    arguments(PitchClass.E, null, 7, 2637.02),
                    arguments(PitchClass.E, Accidental.SHARP, 7, 2793.83),
                    arguments(PitchClass.E, Accidental.FLAT, 8, 4978.03),
                    arguments(PitchClass.E, null, 8, 5274.04),
                    arguments(PitchClass.E, Accidental.SHARP, 8, 5587.65),
                    arguments(PitchClass.F, Accidental.FLAT, 0, 20.6),
                    arguments(PitchClass.F, null, 0, 21.83),
                    arguments(PitchClass.F, Accidental.SHARP, 0, 23.12),
                    arguments(PitchClass.F, Accidental.FLAT, 1, 41.2),
                    arguments(PitchClass.F, null, 1, 43.65),
                    arguments(PitchClass.F, Accidental.SHARP, 1, 46.25),
                    arguments(PitchClass.F, Accidental.FLAT, 2, 82.41),
                    arguments(PitchClass.F, null, 2, 87.31),
                    arguments(PitchClass.F, Accidental.SHARP, 2, 92.5),
                    arguments(PitchClass.F, Accidental.FLAT, 3, 164.81),
                    arguments(PitchClass.F, null, 3, 174.61),
                    arguments(PitchClass.F, Accidental.SHARP, 3, 185),
                    arguments(PitchClass.F, Accidental.FLAT, 4, 329.63),
                    arguments(PitchClass.F, null, 4, 349.23),
                    arguments(PitchClass.F, Accidental.SHARP, 4, 369.99),
                    arguments(PitchClass.F, Accidental.FLAT, 5, 659.25),
                    arguments(PitchClass.F, null, 5, 698.46),
                    arguments(PitchClass.F, Accidental.SHARP, 5, 739.99),
                    arguments(PitchClass.F, Accidental.FLAT, 6, 1318.51),
                    arguments(PitchClass.F, null, 6, 1396.91),
                    arguments(PitchClass.F, Accidental.SHARP, 6, 1479.98),
                    arguments(PitchClass.F, Accidental.FLAT, 7, 2637.02),
                    arguments(PitchClass.F, null, 7, 2793.83),
                    arguments(PitchClass.F, Accidental.SHARP, 7, 2959.96),
                    arguments(PitchClass.F, Accidental.FLAT, 8, 5274.04),
                    arguments(PitchClass.F, null, 8, 5587.65),
                    arguments(PitchClass.F, Accidental.SHARP, 8, 5919.91),
                    arguments(PitchClass.G, Accidental.FLAT, 0, 23.12),
                    arguments(PitchClass.G, null, 0, 24.5),
                    arguments(PitchClass.G, Accidental.SHARP, 0, 25.96),
                    arguments(PitchClass.G, Accidental.FLAT, 1, 46.25),
                    arguments(PitchClass.G, null, 1, 49),
                    arguments(PitchClass.G, Accidental.SHARP, 1, 51.91),
                    arguments(PitchClass.G, Accidental.FLAT, 2, 92.5),
                    arguments(PitchClass.G, null, 2, 98),
                    arguments(PitchClass.G, Accidental.SHARP, 2, 103.83),
                    arguments(PitchClass.G, Accidental.FLAT, 3, 185),
                    arguments(PitchClass.G, null, 3, 196),
                    arguments(PitchClass.G, Accidental.SHARP, 3, 207.65),
                    arguments(PitchClass.G, Accidental.FLAT, 4, 369.99),
                    arguments(PitchClass.G, null, 4, 392),
                    arguments(PitchClass.G, Accidental.SHARP, 4, 415.3),
                    arguments(PitchClass.G, Accidental.FLAT, 5, 739.99),
                    arguments(PitchClass.G, null, 5, 783.99),
                    arguments(PitchClass.G, Accidental.SHARP, 5, 830.61),
                    arguments(PitchClass.G, Accidental.FLAT, 6, 1479.98),
                    arguments(PitchClass.G, null, 6, 1567.98),
                    arguments(PitchClass.G, Accidental.SHARP, 6, 1661.22),
                    arguments(PitchClass.G, Accidental.FLAT, 7, 2959.96),
                    arguments(PitchClass.G, null, 7, 3135.96),
                    arguments(PitchClass.G, Accidental.SHARP, 7, 3322.44),
                    arguments(PitchClass.G, Accidental.FLAT, 8, 5919.91),
                    arguments(PitchClass.G, null, 8, 6271.93),
                    arguments(PitchClass.G, Accidental.SHARP, 8, 6644.88));
        }
    }

    final static class PitchFrequency implements ArgumentsProvider {
        @Override
        public Stream<Arguments> provideArguments(ExtensionContext context) {
            return Stream.of(
                    arguments(new Pitch(PitchClass.A, Accidental.FLAT, 0), 25.96),
                    arguments(new Pitch(PitchClass.A, Accidental.NATURAL, 0), 27.5),
                    arguments(new Pitch(PitchClass.A, Accidental.SHARP, 0), 29.14),
                    arguments(new Pitch(PitchClass.A, Accidental.FLAT, 1), 51.91),
                    arguments(new Pitch(PitchClass.A, Accidental.NATURAL, 1), 55),
                    arguments(new Pitch(PitchClass.A, Accidental.SHARP, 1), 58.27),
                    arguments(new Pitch(PitchClass.A, Accidental.FLAT, 2), 103.83),
                    arguments(new Pitch(PitchClass.A, Accidental.NATURAL, 2), 110),
                    arguments(new Pitch(PitchClass.A, Accidental.SHARP, 2), 116.54),
                    arguments(new Pitch(PitchClass.A, Accidental.FLAT, 3), 207.65),
                    arguments(new Pitch(PitchClass.A, Accidental.NATURAL, 3), 220),
                    arguments(new Pitch(PitchClass.A, Accidental.SHARP, 3), 233.08),
                    arguments(new Pitch(PitchClass.A, Accidental.FLAT, 4), 415.3),
                    arguments(new Pitch(PitchClass.A, Accidental.NATURAL, 4), 440),
                    arguments(new Pitch(PitchClass.A, Accidental.SHARP, 4), 466.16),
                    arguments(new Pitch(PitchClass.A, Accidental.FLAT, 5), 830.61),
                    arguments(new Pitch(PitchClass.A, Accidental.NATURAL, 5), 880),
                    arguments(new Pitch(PitchClass.A, Accidental.SHARP, 5), 932.33),
                    arguments(new Pitch(PitchClass.A, Accidental.FLAT, 6), 1661.22),
                    arguments(new Pitch(PitchClass.A, Accidental.NATURAL, 6), 1760),
                    arguments(new Pitch(PitchClass.A, Accidental.SHARP, 6), 1864.66),
                    arguments(new Pitch(PitchClass.A, Accidental.FLAT, 7), 3322.44),
                    arguments(new Pitch(PitchClass.A, Accidental.NATURAL, 7), 3520),
                    arguments(new Pitch(PitchClass.A, Accidental.SHARP, 7), 3729.31),
                    arguments(new Pitch(PitchClass.A, Accidental.FLAT, 8), 6644.88),
                    arguments(new Pitch(PitchClass.A, Accidental.NATURAL, 8), 7040),
                    arguments(new Pitch(PitchClass.A, Accidental.SHARP, 8), 7458.62),
                    arguments(new Pitch(PitchClass.B, Accidental.FLAT, 0), 29.14),
                    arguments(new Pitch(PitchClass.B, Accidental.NATURAL, 0), 30.87),
                    arguments(new Pitch(PitchClass.B, Accidental.SHARP, 0), 32.7),
                    arguments(new Pitch(PitchClass.B, Accidental.FLAT, 1), 58.27),
                    arguments(new Pitch(PitchClass.B, Accidental.NATURAL, 1), 61.74),
                    arguments(new Pitch(PitchClass.B, Accidental.SHARP, 1), 65.41),
                    arguments(new Pitch(PitchClass.B, Accidental.FLAT, 2), 116.54),
                    arguments(new Pitch(PitchClass.B, Accidental.NATURAL, 2), 123.47),
                    arguments(new Pitch(PitchClass.B, Accidental.SHARP, 2), 130.81),
                    arguments(new Pitch(PitchClass.B, Accidental.FLAT, 3), 233.08),
                    arguments(new Pitch(PitchClass.B, Accidental.NATURAL, 3), 246.95),
                    arguments(new Pitch(PitchClass.B, Accidental.SHARP, 3), 261.63),
                    arguments(new Pitch(PitchClass.B, Accidental.FLAT, 4), 466.16),
                    arguments(new Pitch(PitchClass.B, Accidental.NATURAL, 4), 493.88),
                    arguments(new Pitch(PitchClass.B, Accidental.SHARP, 4), 523.25),
                    arguments(new Pitch(PitchClass.B, Accidental.FLAT, 5), 932.33),
                    arguments(new Pitch(PitchClass.B, Accidental.NATURAL, 5), 987.77),
                    arguments(new Pitch(PitchClass.B, Accidental.SHARP, 5), 1046.5),
                    arguments(new Pitch(PitchClass.B, Accidental.FLAT, 6), 1864.66),
                    arguments(new Pitch(PitchClass.B, Accidental.NATURAL, 6), 1975.53),
                    arguments(new Pitch(PitchClass.B, Accidental.SHARP, 6), 2093),
                    arguments(new Pitch(PitchClass.B, Accidental.FLAT, 7), 3729.31),
                    arguments(new Pitch(PitchClass.B, Accidental.NATURAL, 7), 3951.07),
                    arguments(new Pitch(PitchClass.B, Accidental.SHARP, 7), 4186.01),
                    arguments(new Pitch(PitchClass.B, Accidental.FLAT, 8), 7458.62),
                    arguments(new Pitch(PitchClass.B, Accidental.NATURAL, 8), 7902.13),
                    arguments(new Pitch(PitchClass.B, Accidental.SHARP, 8), 8372.02),
                    arguments(new Pitch(PitchClass.C, Accidental.FLAT, 0), 15.43),
                    arguments(new Pitch(PitchClass.C, Accidental.NATURAL, 0), 16.35),
                    arguments(new Pitch(PitchClass.C, Accidental.SHARP, 0), 17.32),
                    arguments(new Pitch(PitchClass.C, Accidental.FLAT, 1), 30.87),
                    arguments(new Pitch(PitchClass.C, Accidental.NATURAL, 1), 32.7),
                    arguments(new Pitch(PitchClass.C, Accidental.SHARP, 1), 34.65),
                    arguments(new Pitch(PitchClass.C, Accidental.FLAT, 2), 61.74),
                    arguments(new Pitch(PitchClass.C, Accidental.NATURAL, 2), 65.41),
                    arguments(new Pitch(PitchClass.C, Accidental.SHARP, 2), 69.3),
                    arguments(new Pitch(PitchClass.C, Accidental.FLAT, 3), 123.47),
                    arguments(new Pitch(PitchClass.C, Accidental.NATURAL, 3), 130.81),
                    arguments(new Pitch(PitchClass.C, Accidental.SHARP, 3), 138.59),
                    arguments(new Pitch(PitchClass.C, Accidental.FLAT, 4), 246.94),
                    arguments(new Pitch(PitchClass.C, Accidental.NATURAL, 4), 261.63),
                    arguments(new Pitch(PitchClass.C, Accidental.SHARP, 4), 277.18),
                    arguments(new Pitch(PitchClass.C, Accidental.FLAT, 5), 493.88),
                    arguments(new Pitch(PitchClass.C, Accidental.NATURAL, 5), 523.25),
                    arguments(new Pitch(PitchClass.C, Accidental.SHARP, 5), 554.37),
                    arguments(new Pitch(PitchClass.C, Accidental.FLAT, 6), 987.77),
                    arguments(new Pitch(PitchClass.C, Accidental.NATURAL, 6), 1046.5),
                    arguments(new Pitch(PitchClass.C, Accidental.SHARP, 6), 1108.73),
                    arguments(new Pitch(PitchClass.C, Accidental.FLAT, 7), 1975.53),
                    arguments(new Pitch(PitchClass.C, Accidental.NATURAL, 7), 2093),
                    arguments(new Pitch(PitchClass.C, Accidental.SHARP, 7), 2217.46),
                    arguments(new Pitch(PitchClass.C, Accidental.FLAT, 8), 3951.07),
                    arguments(new Pitch(PitchClass.C, Accidental.NATURAL, 8), 4186.01),
                    arguments(new Pitch(PitchClass.C, Accidental.SHARP, 8), 4434.92),
                    arguments(new Pitch(PitchClass.D, Accidental.FLAT, 0), 17.32),
                    arguments(new Pitch(PitchClass.D, Accidental.NATURAL, 0), 18.35),
                    arguments(new Pitch(PitchClass.D, Accidental.SHARP, 0), 19.45),
                    arguments(new Pitch(PitchClass.D, Accidental.FLAT, 1), 34.65),
                    arguments(new Pitch(PitchClass.D, Accidental.NATURAL, 1), 36.71),
                    arguments(new Pitch(PitchClass.D, Accidental.SHARP, 1), 38.89),
                    arguments(new Pitch(PitchClass.D, Accidental.FLAT, 2), 69.3),
                    arguments(new Pitch(PitchClass.D, Accidental.NATURAL, 2), 73.42),
                    arguments(new Pitch(PitchClass.D, Accidental.SHARP, 2), 77.78),
                    arguments(new Pitch(PitchClass.D, Accidental.FLAT, 3), 138.59),
                    arguments(new Pitch(PitchClass.D, Accidental.NATURAL, 3), 146.83),
                    arguments(new Pitch(PitchClass.D, Accidental.SHARP, 3), 155.56),
                    arguments(new Pitch(PitchClass.D, Accidental.FLAT, 4), 277.18),
                    arguments(new Pitch(PitchClass.D, Accidental.NATURAL, 4), 293.66),
                    arguments(new Pitch(PitchClass.D, Accidental.SHARP, 4), 311.13),
                    arguments(new Pitch(PitchClass.D, Accidental.FLAT, 5), 554.37),
                    arguments(new Pitch(PitchClass.D, Accidental.NATURAL, 5), 587.33),
                    arguments(new Pitch(PitchClass.D, Accidental.SHARP, 5), 622.25),
                    arguments(new Pitch(PitchClass.D, Accidental.FLAT, 6), 1108.73),
                    arguments(new Pitch(PitchClass.D, Accidental.NATURAL, 6), 1174.66),
                    arguments(new Pitch(PitchClass.D, Accidental.SHARP, 6), 1244.51),
                    arguments(new Pitch(PitchClass.D, Accidental.FLAT, 7), 2217.46),
                    arguments(new Pitch(PitchClass.D, Accidental.NATURAL, 7), 2349.32),
                    arguments(new Pitch(PitchClass.D, Accidental.SHARP, 7), 2489.02),
                    arguments(new Pitch(PitchClass.D, Accidental.FLAT, 8), 4434.92),
                    arguments(new Pitch(PitchClass.D, Accidental.NATURAL, 8), 4698.63),
                    arguments(new Pitch(PitchClass.D, Accidental.SHARP, 8), 4978.03),
                    arguments(new Pitch(PitchClass.E, Accidental.FLAT, 0), 19.45),
                    arguments(new Pitch(PitchClass.E, Accidental.NATURAL, 0), 20.6),
                    arguments(new Pitch(PitchClass.E, Accidental.SHARP, 0), 21.83),
                    arguments(new Pitch(PitchClass.E, Accidental.FLAT, 1), 38.89),
                    arguments(new Pitch(PitchClass.E, Accidental.NATURAL, 1), 41.2),
                    arguments(new Pitch(PitchClass.E, Accidental.SHARP, 1), 43.65),
                    arguments(new Pitch(PitchClass.E, Accidental.FLAT, 2), 77.78),
                    arguments(new Pitch(PitchClass.E, Accidental.NATURAL, 2), 82.41),
                    arguments(new Pitch(PitchClass.E, Accidental.SHARP, 2), 87.31),
                    arguments(new Pitch(PitchClass.E, Accidental.FLAT, 3), 155.56),
                    arguments(new Pitch(PitchClass.E, Accidental.NATURAL, 3), 164.81),
                    arguments(new Pitch(PitchClass.E, Accidental.SHARP, 3), 174.61),
                    arguments(new Pitch(PitchClass.E, Accidental.FLAT, 4), 311.13),
                    arguments(new Pitch(PitchClass.E, Accidental.NATURAL, 4), 329.63),
                    arguments(new Pitch(PitchClass.E, Accidental.SHARP, 4), 349.23),
                    arguments(new Pitch(PitchClass.E, Accidental.FLAT, 5), 622.25),
                    arguments(new Pitch(PitchClass.E, Accidental.NATURAL, 5), 659.25),
                    arguments(new Pitch(PitchClass.E, Accidental.SHARP, 5), 698.46),
                    arguments(new Pitch(PitchClass.E, Accidental.FLAT, 6), 1244.51),
                    arguments(new Pitch(PitchClass.E, Accidental.NATURAL, 6), 1318.51),
                    arguments(new Pitch(PitchClass.E, Accidental.SHARP, 6), 1396.91),
                    arguments(new Pitch(PitchClass.E, Accidental.FLAT, 7), 2489.02),
                    arguments(new Pitch(PitchClass.E, Accidental.NATURAL, 7), 2637.02),
                    arguments(new Pitch(PitchClass.E, Accidental.SHARP, 7), 2793.83),
                    arguments(new Pitch(PitchClass.E, Accidental.FLAT, 8), 4978.03),
                    arguments(new Pitch(PitchClass.E, Accidental.NATURAL, 8), 5274.04),
                    arguments(new Pitch(PitchClass.E, Accidental.SHARP, 8), 5587.65),
                    arguments(new Pitch(PitchClass.F, Accidental.FLAT, 0), 20.6),
                    arguments(new Pitch(PitchClass.F, Accidental.NATURAL, 0), 21.83),
                    arguments(new Pitch(PitchClass.F, Accidental.SHARP, 0), 23.12),
                    arguments(new Pitch(PitchClass.F, Accidental.FLAT, 1), 41.2),
                    arguments(new Pitch(PitchClass.F, Accidental.NATURAL, 1), 43.65),
                    arguments(new Pitch(PitchClass.F, Accidental.SHARP, 1), 46.25),
                    arguments(new Pitch(PitchClass.F, Accidental.FLAT, 2), 82.41),
                    arguments(new Pitch(PitchClass.F, Accidental.NATURAL, 2), 87.31),
                    arguments(new Pitch(PitchClass.F, Accidental.SHARP, 2), 92.5),
                    arguments(new Pitch(PitchClass.F, Accidental.FLAT, 3), 164.81),
                    arguments(new Pitch(PitchClass.F, Accidental.NATURAL, 3), 174.61),
                    arguments(new Pitch(PitchClass.F, Accidental.SHARP, 3), 185),
                    arguments(new Pitch(PitchClass.F, Accidental.FLAT, 4), 329.63),
                    arguments(new Pitch(PitchClass.F, Accidental.NATURAL, 4), 349.23),
                    arguments(new Pitch(PitchClass.F, Accidental.SHARP, 4), 369.99),
                    arguments(new Pitch(PitchClass.F, Accidental.FLAT, 5), 659.25),
                    arguments(new Pitch(PitchClass.F, Accidental.NATURAL, 5), 698.46),
                    arguments(new Pitch(PitchClass.F, Accidental.SHARP, 5), 739.99),
                    arguments(new Pitch(PitchClass.F, Accidental.FLAT, 6), 1318.51),
                    arguments(new Pitch(PitchClass.F, Accidental.NATURAL, 6), 1396.91),
                    arguments(new Pitch(PitchClass.F, Accidental.SHARP, 6), 1479.98),
                    arguments(new Pitch(PitchClass.F, Accidental.FLAT, 7), 2637.02),
                    arguments(new Pitch(PitchClass.F, Accidental.NATURAL, 7), 2793.83),
                    arguments(new Pitch(PitchClass.F, Accidental.SHARP, 7), 2959.96),
                    arguments(new Pitch(PitchClass.F, Accidental.FLAT, 8), 5274.04),
                    arguments(new Pitch(PitchClass.F, Accidental.NATURAL, 8), 5587.65),
                    arguments(new Pitch(PitchClass.F, Accidental.SHARP, 8), 5919.91),
                    arguments(new Pitch(PitchClass.G, Accidental.FLAT, 0), 23.12),
                    arguments(new Pitch(PitchClass.G, Accidental.NATURAL, 0), 24.5),
                    arguments(new Pitch(PitchClass.G, Accidental.SHARP, 0), 25.96),
                    arguments(new Pitch(PitchClass.G, Accidental.FLAT, 1), 46.25),
                    arguments(new Pitch(PitchClass.G, Accidental.NATURAL, 1), 49),
                    arguments(new Pitch(PitchClass.G, Accidental.SHARP, 1), 51.91),
                    arguments(new Pitch(PitchClass.G, Accidental.FLAT, 2), 92.5),
                    arguments(new Pitch(PitchClass.G, Accidental.NATURAL, 2), 98),
                    arguments(new Pitch(PitchClass.G, Accidental.SHARP, 2), 103.83),
                    arguments(new Pitch(PitchClass.G, Accidental.FLAT, 3), 185),
                    arguments(new Pitch(PitchClass.G, Accidental.NATURAL, 3), 196),
                    arguments(new Pitch(PitchClass.G, Accidental.SHARP, 3), 207.65),
                    arguments(new Pitch(PitchClass.G, Accidental.FLAT, 4), 369.99),
                    arguments(new Pitch(PitchClass.G, Accidental.NATURAL, 4), 392),
                    arguments(new Pitch(PitchClass.G, Accidental.SHARP, 4), 415.3),
                    arguments(new Pitch(PitchClass.G, Accidental.FLAT, 5), 739.99),
                    arguments(new Pitch(PitchClass.G, Accidental.NATURAL, 5), 783.99),
                    arguments(new Pitch(PitchClass.G, Accidental.SHARP, 5), 830.61),
                    arguments(new Pitch(PitchClass.G, Accidental.FLAT, 6), 1479.98),
                    arguments(new Pitch(PitchClass.G, Accidental.NATURAL, 6), 1567.98),
                    arguments(new Pitch(PitchClass.G, Accidental.SHARP, 6), 1661.22),
                    arguments(new Pitch(PitchClass.G, Accidental.FLAT, 7), 2959.96),
                    arguments(new Pitch(PitchClass.G, Accidental.NATURAL, 7), 3135.96),
                    arguments(new Pitch(PitchClass.G, Accidental.SHARP, 7), 3322.44),
                    arguments(new Pitch(PitchClass.G, Accidental.FLAT, 8), 5919.91),
                    arguments(new Pitch(PitchClass.G, Accidental.NATURAL, 8), 6271.93),
                    arguments(new Pitch(PitchClass.G, Accidental.SHARP, 8), 6644.88));
        }
    }

    final static class NoteOctaveFrequency implements ArgumentsProvider {
        @Override
        public Stream<Arguments> provideArguments(ExtensionContext context) {
            return Stream.of(
                    arguments(PitchClass.A, 0, 27.5),
                    arguments(PitchClass.A, 1, 55),
                    arguments(PitchClass.A, 2, 110),
                    arguments(PitchClass.A, 3, 220),
                    arguments(PitchClass.A, 4, 440),
                    arguments(PitchClass.A, 5, 880),
                    arguments(PitchClass.A, 6, 1760),
                    arguments(PitchClass.A, 7, 3520),
                    arguments(PitchClass.A, 8, 7040),
                    arguments(PitchClass.B, 0, 30.87),
                    arguments(PitchClass.B, 1, 61.74),
                    arguments(PitchClass.B, 2, 123.47),
                    arguments(PitchClass.B, 3, 246.95),
                    arguments(PitchClass.B, 4, 493.88),
                    arguments(PitchClass.B, 5, 987.77),
                    arguments(PitchClass.B, 6, 1975.53),
                    arguments(PitchClass.B, 7, 3951.07),
                    arguments(PitchClass.B, 8, 7902.13),
                    arguments(PitchClass.C, 0, 16.35),
                    arguments(PitchClass.C, 1, 32.7),
                    arguments(PitchClass.C, 2, 65.41),
                    arguments(PitchClass.C, 3, 130.81),
                    arguments(PitchClass.C, 4, 261.63),
                    arguments(PitchClass.C, 5, 523.25),
                    arguments(PitchClass.C, 6, 1046.5),
                    arguments(PitchClass.C, 7, 2093),
                    arguments(PitchClass.C, 8, 4186.01),
                    arguments(PitchClass.D, 0, 18.35),
                    arguments(PitchClass.D, 1, 36.71),
                    arguments(PitchClass.D, 2, 73.42),
                    arguments(PitchClass.D, 3, 146.83),
                    arguments(PitchClass.D, 4, 293.66),
                    arguments(PitchClass.D, 5, 587.33),
                    arguments(PitchClass.D, 6, 1174.66),
                    arguments(PitchClass.D, 7, 2349.32),
                    arguments(PitchClass.D, 8, 4698.63),
                    arguments(PitchClass.E, 0, 20.6),
                    arguments(PitchClass.E, 1, 41.2),
                    arguments(PitchClass.E, 2, 82.41),
                    arguments(PitchClass.E, 3, 164.81),
                    arguments(PitchClass.E, 4, 329.63),
                    arguments(PitchClass.E, 5, 659.25),
                    arguments(PitchClass.E, 6, 1318.51),
                    arguments(PitchClass.E, 7, 2637.02),
                    arguments(PitchClass.E, 8, 5274.04),
                    arguments(PitchClass.F, 0, 21.83),
                    arguments(PitchClass.F, 1, 43.65),
                    arguments(PitchClass.F, 2, 87.31),
                    arguments(PitchClass.F, 3, 174.61),
                    arguments(PitchClass.F, 4, 349.23),
                    arguments(PitchClass.F, 5, 698.46),
                    arguments(PitchClass.F, 6, 1396.91),
                    arguments(PitchClass.F, 7, 2793.83),
                    arguments(PitchClass.F, 8, 5587.65),
                    arguments(PitchClass.G, 0, 24.5),
                    arguments(PitchClass.G, 1, 49),
                    arguments(PitchClass.G, 2, 98),
                    arguments(PitchClass.G, 3, 196),
                    arguments(PitchClass.G, 4, 392),
                    arguments(PitchClass.G, 5, 783.99),
                    arguments(PitchClass.G, 6, 1567.98),
                    arguments(PitchClass.G, 7, 3135.96),
                    arguments(PitchClass.G, 8, 6271.93));
        }
    }
}

final class FrequencyTest {
    final static RandomGenerator random = RandomGenerator.getDefault();

    @ParameterizedTest(name = "Frequency.from(Note.{0}, {1}, {2}) ≅ {3}")
    @ArgumentsSource(FrequencyTestArgsProvider.NoteAccidentalOctaveFrequency.class)
    void frequencyFromNoteAccidentalOctave(PitchClass note, Accidental accidental, int octave,
            double expectedFrequency) {
        final double frequency = Frequency.from(note, accidental, octave);
        assertThat(frequency, is(closeTo(expectedFrequency, 0.01)));
    }

    @ParameterizedTest(name = "Frequency.from(Note.{0}, {1}) ≅ {2}")
    @ArgumentsSource(FrequencyTestArgsProvider.NoteOctaveFrequency.class)
    void frequencyFromNoteOctave(PitchClass note, int octave, double expectedFrequency) {
        final double frequency = Frequency.from(note, octave);
        assertThat(frequency, is(closeTo(expectedFrequency, 0.01)));
    }

    @ParameterizedTest(name = "Frequency.from({0}) ≅ {1}")
    @ArgumentsSource(FrequencyTestArgsProvider.PitchFrequency.class)
    void frequencyFromPitch(Pitch pitch, double expectedFrequency) {
        final double frequency = Frequency.from(pitch);
        assertThat(frequency, is(closeTo(expectedFrequency, 0.01)));
    }

    @Test
    @DisplayName("Frequency.from(Note.C, null, # < 0) throws")
    void frequencyFromNegativeOctaveThrows() {
        assertThrows(IllegalArgumentException.class, () -> Frequency.from(PitchClass.C, null, random.nextInt(-12, 0)));
    }

    @Test
    @DisplayName("Frequency.from(null, Accidental, # >= 0) throws")
    void frequencyFromNullNoteThrows() {
        assertThrows(IllegalArgumentException.class, () -> Frequency.from(null,
                random.nextBoolean() ? Accidental.SHARP : Accidental.FLAT, random.nextInt(13)));
    }
}
