package sogott.beep;

import java.util.stream.Stream;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ArgumentsSource;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.closeTo;
import static org.junit.jupiter.params.provider.Arguments.arguments;

final class FrequencyArgProvider {
    final static class NoteAccidentalOctaveFrequency implements ArgumentsProvider {
        @Override
        public Stream<? extends Arguments> provideArguments(ExtensionContext context) throws Exception {
            return Stream.of(
                    arguments(Note.A, Accidental.FLAT, 0, 25.96),
                    arguments(Note.A, null, 0, 27.5),
                    arguments(Note.A, Accidental.SHARP, 0, 29.14),
                    arguments(Note.A, Accidental.FLAT, 1, 51.91),
                    arguments(Note.A, null, 1, 55),
                    arguments(Note.A, Accidental.SHARP, 1, 58.27),
                    arguments(Note.A, Accidental.FLAT, 2, 103.83),
                    arguments(Note.A, null, 2, 110),
                    arguments(Note.A, Accidental.SHARP, 2, 116.54),
                    arguments(Note.A, Accidental.FLAT, 3, 207.65),
                    arguments(Note.A, null, 3, 220),
                    arguments(Note.A, Accidental.SHARP, 3, 233.08),
                    arguments(Note.A, Accidental.FLAT, 4, 415.3),
                    arguments(Note.A, null, 4, 440),
                    arguments(Note.A, Accidental.SHARP, 4, 466.16),
                    arguments(Note.A, Accidental.FLAT, 5, 830.61),
                    arguments(Note.A, null, 5, 880),
                    arguments(Note.A, Accidental.SHARP, 5, 932.33),
                    arguments(Note.A, Accidental.FLAT, 6, 1661.22),
                    arguments(Note.A, null, 6, 1760),
                    arguments(Note.A, Accidental.SHARP, 6, 1864.66),
                    arguments(Note.A, Accidental.FLAT, 7, 3322.44),
                    arguments(Note.A, null, 7, 3520),
                    arguments(Note.A, Accidental.SHARP, 7, 3729.31),
                    arguments(Note.A, Accidental.FLAT, 8, 6644.88),
                    arguments(Note.A, null, 8, 7040),
                    arguments(Note.A, Accidental.SHARP, 8, 7458.62),
                    arguments(Note.B, Accidental.FLAT, 0, 29.14),
                    arguments(Note.B, null, 0, 30.87),
                    arguments(Note.B, Accidental.SHARP, 0, 32.7),
                    arguments(Note.B, Accidental.FLAT, 1, 58.27),
                    arguments(Note.B, null, 1, 61.74),
                    arguments(Note.B, Accidental.SHARP, 1, 65.41),
                    arguments(Note.B, Accidental.FLAT, 2, 116.54),
                    arguments(Note.B, null, 2, 123.47),
                    arguments(Note.B, Accidental.SHARP, 2, 130.81),
                    arguments(Note.B, Accidental.FLAT, 3, 233.08),
                    arguments(Note.B, null, 3, 246.95),
                    arguments(Note.B, Accidental.SHARP, 3, 261.63),
                    arguments(Note.B, Accidental.FLAT, 4, 466.16),
                    arguments(Note.B, null, 4, 493.88),
                    arguments(Note.B, Accidental.SHARP, 4, 523.25),
                    arguments(Note.B, Accidental.FLAT, 5, 932.33),
                    arguments(Note.B, null, 5, 987.77),
                    arguments(Note.B, Accidental.SHARP, 5, 1046.5),
                    arguments(Note.B, Accidental.FLAT, 6, 1864.66),
                    arguments(Note.B, null, 6, 1975.53),
                    arguments(Note.B, Accidental.SHARP, 6, 2093),
                    arguments(Note.B, Accidental.FLAT, 7, 3729.31),
                    arguments(Note.B, null, 7, 3951.07),
                    arguments(Note.B, Accidental.SHARP, 7, 4186.01),
                    arguments(Note.B, Accidental.FLAT, 8, 7458.62),
                    arguments(Note.B, null, 8, 7902.13),
                    arguments(Note.B, Accidental.SHARP, 8, 8372.02),
                    arguments(Note.C, Accidental.FLAT, 0, 15.43),
                    arguments(Note.C, null, 0, 16.35),
                    arguments(Note.C, Accidental.SHARP, 0, 17.32),
                    arguments(Note.C, Accidental.FLAT, 1, 30.87),
                    arguments(Note.C, null, 1, 32.7),
                    arguments(Note.C, Accidental.SHARP, 1, 34.65),
                    arguments(Note.C, Accidental.FLAT, 2, 61.74),
                    arguments(Note.C, null, 2, 65.41),
                    arguments(Note.C, Accidental.SHARP, 2, 69.3),
                    arguments(Note.C, Accidental.FLAT, 3, 123.47),
                    arguments(Note.C, null, 3, 130.81),
                    arguments(Note.C, Accidental.SHARP, 3, 138.59),
                    arguments(Note.C, Accidental.FLAT, 4, 246.94),
                    arguments(Note.C, null, 4, 261.63),
                    arguments(Note.C, Accidental.SHARP, 4, 277.18),
                    arguments(Note.C, Accidental.FLAT, 5, 493.88),
                    arguments(Note.C, null, 5, 523.25),
                    arguments(Note.C, Accidental.SHARP, 5, 554.37),
                    arguments(Note.C, Accidental.FLAT, 6, 987.77),
                    arguments(Note.C, null, 6, 1046.5),
                    arguments(Note.C, Accidental.SHARP, 6, 1108.73),
                    arguments(Note.C, Accidental.FLAT, 7, 1975.53),
                    arguments(Note.C, null, 7, 2093),
                    arguments(Note.C, Accidental.SHARP, 7, 2217.46),
                    arguments(Note.C, Accidental.FLAT, 8, 3951.07),
                    arguments(Note.C, null, 8, 4186.01),
                    arguments(Note.C, Accidental.SHARP, 8, 4434.92),
                    arguments(Note.D, Accidental.FLAT, 0, 17.32),
                    arguments(Note.D, null, 0, 18.35),
                    arguments(Note.D, Accidental.SHARP, 0, 19.45),
                    arguments(Note.D, Accidental.FLAT, 1, 34.65),
                    arguments(Note.D, null, 1, 36.71),
                    arguments(Note.D, Accidental.SHARP, 1, 38.89),
                    arguments(Note.D, Accidental.FLAT, 2, 69.3),
                    arguments(Note.D, null, 2, 73.42),
                    arguments(Note.D, Accidental.SHARP, 2, 77.78),
                    arguments(Note.D, Accidental.FLAT, 3, 138.59),
                    arguments(Note.D, null, 3, 146.83),
                    arguments(Note.D, Accidental.SHARP, 3, 155.56),
                    arguments(Note.D, Accidental.FLAT, 4, 277.18),
                    arguments(Note.D, null, 4, 293.66),
                    arguments(Note.D, Accidental.SHARP, 4, 311.13),
                    arguments(Note.D, Accidental.FLAT, 5, 554.37),
                    arguments(Note.D, null, 5, 587.33),
                    arguments(Note.D, Accidental.SHARP, 5, 622.25),
                    arguments(Note.D, Accidental.FLAT, 6, 1108.73),
                    arguments(Note.D, null, 6, 1174.66),
                    arguments(Note.D, Accidental.SHARP, 6, 1244.51),
                    arguments(Note.D, Accidental.FLAT, 7, 2217.46),
                    arguments(Note.D, null, 7, 2349.32),
                    arguments(Note.D, Accidental.SHARP, 7, 2489.02),
                    arguments(Note.D, Accidental.FLAT, 8, 4434.92),
                    arguments(Note.D, null, 8, 4698.63),
                    arguments(Note.D, Accidental.SHARP, 8, 4978.03),
                    arguments(Note.E, Accidental.FLAT, 0, 19.45),
                    arguments(Note.E, null, 0, 20.6),
                    arguments(Note.E, Accidental.SHARP, 0, 21.83),
                    arguments(Note.E, Accidental.FLAT, 1, 38.89),
                    arguments(Note.E, null, 1, 41.2),
                    arguments(Note.E, Accidental.SHARP, 1, 43.65),
                    arguments(Note.E, Accidental.FLAT, 2, 77.78),
                    arguments(Note.E, null, 2, 82.41),
                    arguments(Note.E, Accidental.SHARP, 2, 87.31),
                    arguments(Note.E, Accidental.FLAT, 3, 155.56),
                    arguments(Note.E, null, 3, 164.81),
                    arguments(Note.E, Accidental.SHARP, 3, 174.61),
                    arguments(Note.E, Accidental.FLAT, 4, 311.13),
                    arguments(Note.E, null, 4, 329.63),
                    arguments(Note.E, Accidental.SHARP, 4, 349.23),
                    arguments(Note.E, Accidental.FLAT, 5, 622.25),
                    arguments(Note.E, null, 5, 659.25),
                    arguments(Note.E, Accidental.SHARP, 5, 698.46),
                    arguments(Note.E, Accidental.FLAT, 6, 1244.51),
                    arguments(Note.E, null, 6, 1318.51),
                    arguments(Note.E, Accidental.SHARP, 6, 1396.91),
                    arguments(Note.E, Accidental.FLAT, 7, 2489.02),
                    arguments(Note.E, null, 7, 2637.02),
                    arguments(Note.E, Accidental.SHARP, 7, 2793.83),
                    arguments(Note.E, Accidental.FLAT, 8, 4978.03),
                    arguments(Note.E, null, 8, 5274.04),
                    arguments(Note.E, Accidental.SHARP, 8, 5587.65));
        }
    }
}

final class FrequencyTest {
    @ParameterizedTest(name = "Frequency.from({0}, {1}, {2}) returns ≅ {3}")
    @ArgumentsSource(FrequencyArgProvider.NoteAccidentalOctaveFrequency.class)
    void cliOptionLongOptValue(Note note, Accidental accidental, int octave, double expectedFrequency) {
        final double frequency = Frequency.from(note, accidental, octave);
        assertThat(frequency, is(closeTo(expectedFrequency, 0.01)));
    }
}
