package sogott.tones;

/**
 * Class consisting exclusively of static methods used to generate {@code byte}
 * arrays that can be used as buffers to generate wave shapes. These methods are
 * used internally by the {@link Wave#generate(double, int)} method and assume
 * a sample rate of 44.1khz.
 *
 * <p>
 * To reduced the likelihood of clicks and pops, and ADSR (attack decay sustain
 * release) envelope is applied to the resulting {@code byte} array buffers
 * generated by the {@link #sine(double, int)} and
 * {@link #triangle(double, int)}
 * methods.
 *
 * @see Wave
 */
final class GenerateWaveByteBuffer {
    private final static float SAMPLE_RATE = 44100;
    private final static short AMPLITUDE = Short.MAX_VALUE;

    // ADR defined in milliseconds
    private final static int ATTACK = 50;
    private final static int DECAY = 50;
    private final static int RELEASE = 50;

    private final static double SUSTAIN = 0.9; // sustain level of max volume (AMPLITUDE)

    /**
     * Generates an empty {@code byte} array buffer (all indexes initialized to
     * 0's) appropriate for silence to be played when outputting to audio.
     *
     * @param duration a positive {@code int} to set the duration in milliseconds
     *                 of the silence.
     *
     * @return A an empty {@code byte} array buffer appropriate for silence to
     *         be played when outputted to audio.
     *
     * @throws IllegalArgumentException If {@code duration} is not positive (0
     *                                  or less).
     */
    static byte[] silence(int duration) {
        if (duration <= 0) {
            throw new IllegalArgumentException("Non positive duration: " + duration);
        }

        final int samples = (int) ((duration / 1000.0) * SAMPLE_RATE);
        return new byte[samples * 2];
    }

    /**
     * Generates a SINE wave with the given {@code frequency} and {@code duration}.
     *
     * @param frequency A positive {@code double} to specify the frequency of
     *                  the generated SINE wave.
     *
     * @param duration  A positive {@code int} to specify the duration, in
     *                  milliseconds, of the generated SINE wave.
     *
     * @return A {@code byte} array buffer of a SINE wave.
     *
     * @throws IllegalArgumentException If either the {@code frequency} or
     *                                  {@code duration} argument isn't positive (0
     *                                  or less).
     */
    static byte[] sine(double frequency, int duration) {
        if (frequency <= 0) {
            throw new IllegalArgumentException("Non positive frequency: " + frequency);
        }

        if (duration <= 0) {
            throw new IllegalArgumentException("Non positive duration: " + duration);
        }

        final int samples = (int) ((duration / 1000.0) * SAMPLE_RATE);
        final byte[] output = new byte[samples * 2]; // 16-bit audio

        final int attackSamples = (int) ((ATTACK / 1000.0) * SAMPLE_RATE);
        final int decaySamples = (int) ((DECAY / 1000.0) * SAMPLE_RATE);
        final int releaseSamples = (int) ((RELEASE / 1000.0) * SAMPLE_RATE);

        final int sustainSamples = samples - (attackSamples + decaySamples + releaseSamples);

        for (int currentSample = 0; currentSample < samples; ++currentSample) {
            final double angle = 2.0 * Math.PI * frequency * currentSample / SAMPLE_RATE;

            double envelope;

            if (currentSample < attackSamples) {
                // Attack phase: gradually increase from 0 to 1
                envelope = (double) currentSample / attackSamples;
            } else if (currentSample < attackSamples + decaySamples) {
                // Decay phase: decrease from 1 to sustain level
                int decaySample = currentSample - attackSamples;
                envelope = 1.0 - (1.0 - SUSTAIN) * ((double) decaySample / decaySamples);
            } else if (currentSample < attackSamples + decaySamples + sustainSamples) {
                // Sustain phase: maintain sustain level
                envelope = SUSTAIN;
            } else {
                // Release phase: decrease from sustain level to 0
                int releaseSample = currentSample - (attackSamples + decaySamples + sustainSamples);
                envelope = SUSTAIN * (1.0 - (double) releaseSample / releaseSamples);
            }

            final short sample = (short) (Math.sin(angle) * AMPLITUDE * envelope);

            // Little endian
            output[2 * currentSample] = (byte) (sample & 0xFF);
            output[2 * currentSample + 1] = (byte) ((sample >> 8) & 0xFF);
        }

        return output;
    }

    /**
     * Generates a SQUARE wave with the given {@code frequency} and
     * {@code duration}.
     *
     * @param frequency A positive {@code double} to specify the frequency of
     *                  the generated SQUARE wave.
     *
     * @param duration  A positive {@code int} to specify the duration, in
     *                  milliseconds, of the generated SQUARE wave.
     *
     * @return A {@code byte} array buffer of a SQUARE wave.
     *
     * @throws IllegalArgumentException If either the {@code frequency} or
     *                                  {@code duration} argument isn't positive (0
     *                                  or less).
     */
    static byte[] square(double frequency, int duration) {
        if (frequency <= 0) {
            throw new IllegalArgumentException("Non positive frequency: " + frequency);
        }

        if (duration <= 0) {
            throw new IllegalArgumentException("Non positive duration: " + duration);
        }

        final int samples = (int) ((duration / 1000.0) * SAMPLE_RATE);
        final byte[] output = new byte[samples * 2]; // 16-bit audio

        for (int currentSample = 0; currentSample < samples; ++currentSample) {
            final double angle = 2.0 * Math.PI * frequency * currentSample / SAMPLE_RATE;
            final short sample = (short) ((Math.sin(angle) >= 0 ? 1 : -1) * AMPLITUDE);

            // Little endian
            output[2 * currentSample] = (byte) (sample & 0xFF);
            output[2 * currentSample + 1] = (byte) ((sample >> 8) & 0xFF);
        }

        return output;
    }

    /**
     * Generates a TRIANGLE wave with the given {@code frequency} and
     * {@code duration}.
     *
     * @param frequency A positive {@code double} to specify the frequency of
     *                  the generated TRIANGLE wave.
     *
     * @param duration  A positive {@code int} to specify the duration, in
     *                  milliseconds, of the generated TRIANGLE wave.
     *
     * @return A {@code byte} array buffer of a TRIANGLE wave.
     *
     * @throws IllegalArgumentException If either the {@code frequency} or
     *                                  {@code duration} argument isn't positive (0
     *                                  or less).
     */
    static byte[] triangle(double frequency, int duration) {
        if (frequency <= 0) {
            throw new IllegalArgumentException("Non positive frequency: " + frequency);
        }

        if (duration <= 0) {
            throw new IllegalArgumentException("Non positive duration: " + duration);
        }

        final int samples = (int) ((duration / 1000.0) * SAMPLE_RATE);
        final double period = SAMPLE_RATE / frequency;
        final byte[] output = new byte[samples * 2]; // 16-bit audio

        final int attackSamples = (int) ((ATTACK / 1000.0) * SAMPLE_RATE);
        final int decaySamples = (int) ((DECAY / 1000.0) * SAMPLE_RATE);
        final int releaseSamples = (int) ((RELEASE / 1000.0) * SAMPLE_RATE);
        final int sustainSamples = samples - (attackSamples + decaySamples + releaseSamples);

        for (int currentSample = 0; currentSample < samples; ++currentSample) {
            final double position = currentSample % period;
            final double value = 2 * Math.abs(2 * (position / period) - 1) - 1;
            final short triangleSample = (short) (value * AMPLITUDE);

            double envelope;
            if (currentSample < attackSamples) {
                // Attack phase: gradually increase from 0 to 1
                envelope = (double) currentSample / attackSamples;
            } else if (currentSample < attackSamples + decaySamples) {
                // Decay phase: decrease from 1 to sustain level
                int decaySample = currentSample - attackSamples;
                envelope = 1.0 - (1.0 - SUSTAIN) * ((double) decaySample / decaySamples);
            } else if (currentSample < attackSamples + decaySamples + sustainSamples) {
                // Sustain phase: maintain sustain level
                envelope = SUSTAIN;
            } else {
                // Release phase: decrease from sustain level to 0
                int releaseSample = currentSample - (attackSamples + decaySamples + sustainSamples);
                envelope = SUSTAIN * (1.0 - (double) releaseSample / releaseSamples);
            }

            final short sample = (short) (triangleSample * envelope);

            // Little endian
            output[2 * currentSample] = (byte) (sample & 0xFF);
            output[2 * currentSample + 1] = (byte) ((sample >> 8) & 0xFF);
        }

        return output;
    }

    /**
     * Generates a SAWTOOTH UP wave with the given {@code frequency} and
     * {@code duration}.
     *
     * @param frequency A positive {@code double} to specify the frequency of
     *                  the generated SAWTOOTH UP wave.
     *
     * @param duration  A positive {@code int} to specify the duration, in
     *                  milliseconds, of the generated SAWTOOTH UP wave.
     *
     * @return A {@code byte} array buffer of a SAWTOOTH UP wave.
     *
     * @throws IllegalArgumentException If either the {@code frequency} or
     *                                  {@code duration} argument isn't positive (0
     *                                  or less).
     */
    static byte[] sawUp(double frequency, int duration) {
        if (frequency <= 0) {
            throw new IllegalArgumentException("Non positive frequency: " + frequency);
        }

        if (duration <= 0) {
            throw new IllegalArgumentException("Non positive duration: " + duration);
        }

        final int samples = (int) ((duration / 1000.0) * SAMPLE_RATE);
        final double period = SAMPLE_RATE / frequency;
        final byte[] output = new byte[samples * 2]; // 16-bit audio

        for (int currentSample = 0; currentSample < samples; ++currentSample) {
            final double position = currentSample % period;
            final double value = (2 * (position / period)) - 1;
            final short sample = (short) (value * AMPLITUDE);

            // Little endian
            output[2 * currentSample] = (byte) (sample & 0xFF);
            output[2 * currentSample + 1] = (byte) ((sample >> 8) & 0xFF);
        }

        return output;
    }

    /**
     * Generates a SAWTOOTH DOWN wave with the given {@code frequency} and
     * {@code duration}.
     *
     * @param frequency A positive {@code double} to specify the frequency of
     *                  the generated SAWTOOTH DOWN wave.
     *
     * @param duration  A positive {@code int} to specify the duration, in
     *                  milliseconds, of the generated SAWTOOTH DOWN wave.
     *
     * @return A {@code byte} array buffer of a SAWTOOTH DOWN wave.
     *
     * @throws IllegalArgumentException If either the {@code frequency} or
     *                                  {@code duration} argument isn't positive (0
     *                                  or less).
     */
    static byte[] sawDown(double frequency, int duration) {
        if (frequency <= 0) {
            throw new IllegalArgumentException("Non positive frequency: " + frequency);
        }

        if (duration <= 0) {
            throw new IllegalArgumentException("Non positive duration: " + duration);
        }

        final int samples = (int) ((duration / 1000.0) * SAMPLE_RATE);
        final double period = SAMPLE_RATE / frequency;
        final byte[] output = new byte[samples * 2]; // 16-bit audio

        for (int currentSample = 0; currentSample < samples; ++currentSample) {
            final double position = currentSample % period;
            final double value = 1 - (2 * (position / period));
            final short sample = (short) (value * AMPLITUDE);

            // Little endian
            output[2 * currentSample] = (byte) (sample & 0xFF);
            output[2 * currentSample + 1] = (byte) ((sample >> 8) & 0xFF);
        }

        return output;
    }

    private GenerateWaveByteBuffer() {
        throw new UnsupportedOperationException(
                GenerateWaveByteBuffer.class.getSimpleName() + " is a static class and cannot be instantiated.");
    }
}
